server:
  port: 7777

spring:
  application:
    name: api

#  datasource:
#    url: jdbc:postgresql://localhost:5432/mon_app
#    username: mon_user
#    password: mon_mot_de_passe
#    driver-class-name: org.postgresql.Driver

#  jpa:
#    hibernate:
#      ddl-auto: update  # ou 'create' pour reset à chaque lancement
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect